# Generated by Django 4.0.6 on 2022-07-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menu')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('MU', 'Must pick one and one only'), ('MM', 'Must pick at least one'), ('OU', 'Must pick zero or one'), ('OM', 'Can pick any number')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('status', models.CharField(choices=[('CO', 'Completed'), ('IP', 'In progress'), ('CA', 'Cancelled')], max_length=2)),
                ('type', models.CharField(choices=[('DE', 'Delivery'), ('SP', 'Self pickup')], max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.rider')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.session')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.order')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_options_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menuitemoptiongroup')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menuitemoption')),
                ('order_item_option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.orderitemoptiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_the_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menuitemoption',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menuitemoptiongroup'),
        ),
        migrations.CreateModel(
            name='MenuHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.restaurant'),
        ),
    ]
