# Generated by Django 4.0.6 on 2022-07-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_menu_is_used_menuhours_day_of_the_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemoptiongroup',
            old_name='menu_item_options_group',
            new_name='menu_item_option_group',
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='restaurant',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='merchant.restaurant'),
            preserve_default=False,
        ),
    ]
