# Generated by Django 4.0.6 on 2022-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_rename_menu_item_options_group_orderitemoptiongroup_menu_item_option_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_the_week',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2),
        ),
    ]
