# Generated by Django 4.0.6 on 2022-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_alter_openinghours_day_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
