# Generated by Django 4.0.2 on 2022-07-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_review_restaurant_alter_client_user_and_more'),
        ('rider', '0001_initial'),
        ('merchant', '0009_remove_menu_is_used_remove_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuhours',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='merchant.restaurant'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='merchant.menu'),
        ),
        migrations.AlterField(
            model_name='menuhours',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_hours', to='merchant.menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchant.menucategory'),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='merchant.menuitemoptiongroup'),
        ),
        migrations.AlterField(
            model_name='menuitemoptiongroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='merchant.menuitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rider.session'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='merchant.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='menu_item_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_options', to='merchant.menuitemoption'),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='order_item_option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='merchant.orderitemoptiongroup'),
        ),
        migrations.AlterField(
            model_name='orderitemoptiongroup',
            name='menu_item_option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_option_groups', to='merchant.menuitemoptiongroup'),
        ),
        migrations.AlterField(
            model_name='orderitemoptiongroup',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='merchant.orderitem'),
        ),
        migrations.AlterField(
            model_name='restaurantstaff',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='merchant.restaurant'),
        ),
    ]
