# Generated by Django 4.0.2 on 2022-07-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_remove_menuhours_restaurant_remove_order_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurnt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merchant.restaurant'),
            preserve_default=False,
        ),
    ]
