# Generated by Django 4.0.2 on 2022-07-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_order_restaurnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurnt',
            new_name='restaurant',
        ),
    ]
