# Generated by Django 4.0.6 on 2022-07-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_session_cancelled'),
        ('merchant', '0015_order_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rider.session'),
        ),
        migrations.CreateModel(
            name='PauseHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('restuarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_hours', to='merchant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('restuarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_hours', to='merchant.restaurant')),
            ],
        ),
    ]
