# Generated by Django 4.0.6 on 2022-07-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0017_pausehours_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayhours',
            old_name='restuarant',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='pausehours',
            old_name='restuarant',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='pausehours',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 8, 29, 53, 467042)),
            preserve_default=False,
        ),
    ]
