# Generated by Django 4.0.2 on 2022-07-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0020_alter_menuitemoptiongroup_type_alter_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='merchant.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='HolidayHours',
        ),
    ]
