# Generated by Django 4.0.6 on 2022-07-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_session_cancelled'),
        ('merchant', '0021_holiday_delete_holidayhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='merchant.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitemoption',
            name='menu_item_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_options', to='merchant.menuitemoption'),
        ),
        migrations.AlterField(
            model_name='orderitemoptiongroup',
            name='menu_item_option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_option_groups', to='merchant.menuitemoptiongroup'),
        ),
        migrations.CreateModel(
            name='SelfPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_pickup_datetime', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='self_pickup', to='merchant.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reason', models.CharField(max_length=50)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='price_adjustment', to='merchant.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_delivery_datetime', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='merchant.order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='rider.session')),
            ],
        ),
    ]
