# Generated by Django 4.0.6 on 2022-08-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_session_cancelled'),
        ('merchant', '0023_alter_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='merchant.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rider.session'),
        ),
    ]
