# Generated by Django 4.0.6 on 2022-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0024_alter_delivery_order_alter_delivery_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider_pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfpickup',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
            preserve_default=False,
        ),
    ]
