# Generated by Django 4.0.6 on 2022-08-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0025_remove_order_completed_delivery_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_datetime',
        ),
        migrations.RemoveField(
            model_name='selfpickup',
            name='pickup_datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
