# Generated by Django 4.0.6 on 2022-08-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0030_alter_delivery_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_cost',
        ),
    ]
