# Generated by Django 4.0.6 on 2022-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0031_remove_delivery_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
            preserve_default=False,
        ),
    ]
