# Generated by Django 4.0.6 on 2022-08-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_session_cancelled'),
        ('merchant', '0033_order_delay_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rider.session'),
        ),
    ]
