# Generated by Django 4.0.2 on 2022-08-13 12:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+6587654321', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
