# Generated by Django 4.0.6 on 2022-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='is_in_active_session',
        ),
    ]
