# Generated by Django 4.0.6 on 2022-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_remove_rider_is_in_active_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
