# Generated by Django 4.0.6 on 2022-08-11 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_session_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
