# Generated by Django 4.0.6 on 2022-08-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_alter_session_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cancelled',
        ),
    ]
